Supercarrier aliases missing AircraftAliases
DCS-Skunkworks/dcs-bios pull request #573
Opened 2024-05-02 21:16 UTC by emcek

Looks like `SuperCarrier.json` is missing in `AircraftAliases.json`

2024-05-02 21:23 UTC, charliefoxtwo commented
AircraftAliases.json is an auto-generated file, so if this were an issue we should probably address this at the source rather than here. However, I believe this is intentional as the supercarrier itself is not a playable module (just like the NS430).

That said, again like the NS430, I believe the supercarrier should appear in the export list for all playable modules, so perhaps that could be a problem.

Was there a specific issue you were encountering?

2024-05-03 09:40 UTC, emcek commented
> AircraftAliases.json is an auto-generated file, so if this were an issue we should probably address this at the source rather than here. However, I believe this is intentional as the supercarrier itself is not a playable module (just like the NS430).
> 
> That said, again like the NS430, I believe the supercarrier should appear in the export list for all playable modules, so perhaps that could be a problem.
So, should I check codebase and try add `Supercarrier` as playable module?

> Was there a specific issue you were encountering?
Nothing special, I was checking `AircraftAliases.json` and this case looked odd to me.

2024-05-03 14:11 UTC, charliefoxtwo commented
No, the supercarrier should not be added as a playable module (as it's not - you can't start a mission as a supercarrier pilot lol).

When a user is in a mission, they are using a single playable module. For example, if they start with the F18 on the supercarrier, their playable module would be the F18, and bios will export data for the F18 module addresses. Bios will also export MetadataStart, MetadataEnd, and CommonData module addresses, as they're common to all aircraft. We just also need to make sure the supercarrier is treated like CommonData basically, so that it's exported with all modules (though, I wonder what happens if a map has multiple supercarriers 🤔)

2024-05-12 17:48 UTC, charliefoxtwo requested changes
Marking this as request changes so we know not to merge in its current state (this file is autogenerated, and any changes would immediately be overwritten on starting a mission).

If any incorrect/buggy behavior is occurring, perhaps an issue should be opened to discuss further? Though I'll be honest, given the current state of the supercarrier and lack of any controls I don't know that it's worth spending too much time on at this stage.

2024-05-12 17:48 UTC, charliefoxtwo commented on Scripts/DCS-BIOS/doc/json/AircraftAliases.json
> +          "Supercarrier": [ "CommonData", "SuperCarrier" ],
SuperCarrier should not be added here, as it's not a playable module

2024-06-23 23:47 UTC, charliefoxtwo commented
Looked into this a little further - the reason SuperCarrier isn't in AircraftAliases.lua is because it's not exported by default
https://github.com/DCS-Skunkworks/dcs-bios/blob/ec3bf2cf8872d2d4debd32169c24ddf1d714aaf3/Scripts/DCS-BIOS/BIOS.lua#L66

I believe there were issues with the exports last time we tried, so it has stayed disabled. We can revisit this though.

2024-07-06 14:23 UTC, charliefoxtwo commented
I plan to revisit this once the next patch drops, as the planned addition of the air boss station may change the way the supercarrier operates with respect to dcs-bios.

2024-07-07 04:28 UTC, charliefoxtwo commented
I'm going to go ahead and close this PR since to my knowledge there's no way to get data out of the Supercarrier currently, and as such the module should stay disabled. Hopefully in the future we'll be able to get the data from it though!

2024-07-07 04:28 UTC, closed without merging